-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.doctors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  nombre text,
  created_at timestamp with time zone DEFAULT now(),
  profesion text,
  especialidad text,
  telefono text,
  documento text,
  sexo text,
  estado_civil text,
  obra_social text,
  metadata jsonb,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  email text,
  fecha_nacimiento date,
  nacionalidad text,
  direccion text,
  ciudad text,
  provincia text,
  foto_url text,
  matricula text,
  tipo_matricula text,
  CONSTRAINT doctors_pkey PRIMARY KEY (id),
  CONSTRAINT doctors_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.pacientes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre text NOT NULL,
  apellido text NOT NULL,
  dni text NOT NULL UNIQUE,
  fecha_nacimiento date,
  sexo text,
  direccion text,
  telefono text,
  email text,
  obra_social text,
  numero_afiliado text,
  contacto_emergencia_nombre text,
  contacto_emergencia_telefono text,
  user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pacientes_pkey PRIMARY KEY (id),
  CONSTRAINT pacientes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.antecedentes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  paciente_id uuid NOT NULL,
  tipo USER-DEFINED NOT NULL,
  descripcion text NOT NULL,
  fecha_registro date NOT NULL DEFAULT CURRENT_DATE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT antecedentes_pkey PRIMARY KEY (id),
  CONSTRAINT antecedentes_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES public.pacientes(id)
);
CREATE TABLE public.consultas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  paciente_id uuid NOT NULL,
  fecha timestamp with time zone NOT NULL DEFAULT now(),
  motivo_consulta text,
  examen_fisico text,
  observaciones text,
  profesional_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT consultas_pkey PRIMARY KEY (id),
  CONSTRAINT consultas_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES public.pacientes(id),
  CONSTRAINT consultas_profesional_id_fkey FOREIGN KEY (profesional_id) REFERENCES public.doctors(id)
);
CREATE TABLE public.diagnosticos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  consulta_id uuid NOT NULL,
  paciente_id uuid NOT NULL,
  descripcion text NOT NULL,
  codigo_cie10 text,
  fecha date NOT NULL DEFAULT CURRENT_DATE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT diagnosticos_pkey PRIMARY KEY (id),
  CONSTRAINT diagnosticos_consulta_id_fkey FOREIGN KEY (consulta_id) REFERENCES public.consultas(id),
  CONSTRAINT diagnosticos_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES public.pacientes(id)
);
CREATE TABLE public.medicaciones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  paciente_id uuid NOT NULL,
  consulta_id uuid,
  nombre_medicamento text NOT NULL,
  dosis text,
  frecuencia text,
  fecha_inicio date,
  fecha_fin date,
  cronica boolean NOT NULL DEFAULT false,
  activa boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT medicaciones_pkey PRIMARY KEY (id),
  CONSTRAINT medicaciones_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES public.pacientes(id),
  CONSTRAINT medicaciones_consulta_id_fkey FOREIGN KEY (consulta_id) REFERENCES public.consultas(id)
);
CREATE TABLE public.recetas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  consulta_id uuid,
  paciente_id uuid NOT NULL,
  fecha_emision date NOT NULL DEFAULT CURRENT_DATE,
  pdf_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT recetas_pkey PRIMARY KEY (id),
  CONSTRAINT recetas_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES public.pacientes(id),
  CONSTRAINT recetas_consulta_id_fkey FOREIGN KEY (consulta_id) REFERENCES public.consultas(id)
);
CREATE TABLE public.receta_medicaciones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  receta_id uuid NOT NULL,
  nombre_medicamento text NOT NULL,
  dosis text,
  frecuencia text,
  instrucciones text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT receta_medicaciones_pkey PRIMARY KEY (id),
  CONSTRAINT receta_medicaciones_receta_id_fkey FOREIGN KEY (receta_id) REFERENCES public.recetas(id)
);
CREATE TABLE public.estudios (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  paciente_id uuid NOT NULL,
  consulta_id uuid,
  titulo text NOT NULL,
  categoria USER-DEFINED NOT NULL DEFAULT 'otro'::estudio_categoria,
  fecha date NOT NULL DEFAULT CURRENT_DATE,
  archivo_url text,
  es_descargable boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT estudios_pkey PRIMARY KEY (id),
  CONSTRAINT estudios_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES public.pacientes(id),
  CONSTRAINT estudios_consulta_id_fkey FOREIGN KEY (consulta_id) REFERENCES public.consultas(id)
);
CREATE TABLE public.turnos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  paciente_id uuid,
  doctor_id uuid,
  paciente_user_id uuid,
  nombre text,
  apellido text,
  email text,
  telefono text,
  motivo text,
  fecha_preferida date,
  hora_preferida time without time zone,
  duracion_minutos integer NOT NULL DEFAULT 30 CHECK (duracion_minutos > 0 AND duracion_minutos <= 240),
  estado text NOT NULL DEFAULT 'pendiente'::text,
  tipo_consulta text,
  es_particular boolean NOT NULL DEFAULT false,
  obra_social text,
  meet_link text,
  video_room text,
  video_started_at timestamp with time zone,
  video_ended_at timestamp with time zone,
  video_status text NOT NULL DEFAULT 'pending'::text,
  fecha_hora_inicio_real timestamp with time zone,
  fecha_hora_fin_real timestamp with time zone,
  recordatorio_enviado boolean NOT NULL DEFAULT false,
  metadata jsonb,
  consulta_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT turnos_pkey PRIMARY KEY (id),
  CONSTRAINT turnos_paciente_id_fkey FOREIGN KEY (paciente_id) REFERENCES public.pacientes(id),
  CONSTRAINT turnos_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.doctors(id),
  CONSTRAINT turnos_paciente_user_id_fkey FOREIGN KEY (paciente_user_id) REFERENCES auth.users(id),
  CONSTRAINT turnos_consulta_id_fkey FOREIGN KEY (consulta_id) REFERENCES public.consultas(id)
);